# This docker-compose file allows you to run db in docker
# For convenience, you can create symlink to docker-compose.yml
#
# Do not use this file in production!
# See https://github.com/po8klasie/infra for info on how to set up prod-ready deployment
version: '3.1'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
