version: '3.8'

services:
  linter-and-tests:
    image: ${IMAGE_FOR_TESTS}
    depends_on: 
      - database
    environment:
      PARALLEL_WORKERS: 1 # makes tests run sequentially instead of simultaneously
    networks:
      - po8klasie
    entrypoint: .ci/entrypoint.ci.sh
      
  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_USER: postgres
    networks:
      - po8klasie
networks:
  po8klasie:
