default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  password: postgres
  host: localhost
  database: development

test:
  <<: *default
  #The host for the database is database in compose networking in ci, locally you have
  #to set the DATABASE_HOST env variable to localhost
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST") { "database" } %>
  database: test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
