default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: workspace_development

test:
  <<: *default
  database: workspace_test

production:
  <<: *default
  database: workspace_production
  username: workspace
  password: <%= ENV['WORKSPACE_DATABASE_PASSWORD'] %>
