name: Test building
on:
  pull_request:

concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner
    
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        install: true

    - name: Prepare Tags
      id: tags
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="dev/test"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}
         
    - name: Setup docker cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build code
      uses: docker/build-push-action@v2
      with:
        push: false
        file: Dockerfile
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache # TODO: Cache from master (ghcr)
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        tags: ${{ steps.tags.outputs.tagged_image }}

    - name: Run Tests
      env:
        TESTS_IMAGE_TAG: ${{ steps.tags.outputs.tagged_image }}
      run: |
        docker-compose -f .ci/docker-compose.ci.yml run linter-and-tests --exit-code-from linter-and-tests
      
    # Temp fix for growing cache
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
